import os
import sys
import numpy as np

from dotenv import load_dotenv
from typing import Iterable, Literal

sys.path.insert(
    0,
    os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../")),
)

from src.index.spliters import split_paragraphs, split_sentences
from src.core.types import (
    DocumentPayload,
    NodeKind,
    ParagraphPayload,
    SectionPayload,
    SentencePayload,
    StoredNode,
    TreeNode,
)
from z_utils.logging_config import get_logger
from z_utils.embeddings import OpenAIEmbeddingModel, average_embeddings

load_dotenv()
logger = get_logger(__name__)
# 段落嵌入模式类型定义
ParagraphEmbeddingMode = Literal["averaged", "full", "both"]


def sentence_payloads_from_text(text: str) -> list[SentencePayload]:
    """将文本拆分为句子"""
    return [SentencePayload(text=s) for s in split_sentences(text)]


def paragraph_payload_from_text(text: str) -> ParagraphPayload:
    """将纯文本转换为包含句子分割的段落"""
    return ParagraphPayload(
        text=text,
        sentences=sentence_payloads_from_text(text),
    )


def sections_from_text(document: DocumentPayload) -> list[SectionPayload]:
    """为非结构化文档文本自动生成单个章节"""
    paragraphs = [
        paragraph_payload_from_text(paragraph)
        for paragraph in split_paragraphs(document.text)
    ]
    return [
        SectionPayload(
            title=document.title,
            paragraphs=paragraphs,
            metadata={"autogenerated": True},
        )
    ]


class DocumentIndexer:
    """
    从 DocumentPayload 构建分层节点并计算嵌入向量。

    将文档结构化为文档 → 章节 → 段落 → 句子的层级树，doc:sec1:p1:s1
    并为各节点计算嵌入向量，最终输出可存储的节点列表。

    参数:
        embedding_model: 使用的嵌入模型。
        paragraph_embedding_mode: 段落嵌入处理模式：
            - "averaged": 使用句子嵌入的加权平均值（默认）
            - "full": 直接对整个段落文本进行嵌入
            - "both": 同时存储平均嵌入（主嵌入）和完整嵌入（存于元数据中）
    """

    def __init__(
        self,
        embedding_model: OpenAIEmbeddingModel | None = None,
        paragraph_embedding_mode: ParagraphEmbeddingMode = "averaged",
    ) -> None:
        self._embedding_model = embedding_model
        self._paragraph_embedding_mode = paragraph_embedding_mode

    async def index(self, document: DocumentPayload) -> list[StoredNode]:
        """构建分层树、计算嵌入向量，并返回可存储的节点列表。"""
        root = self._build_tree(document)
        await self._embed_tree(root)
        return [self._to_stored(node) for node in self._flatten(root)]

    def _build_tree(self, document: DocumentPayload) -> TreeNode:
        """构建文档 → 章节 → 段落 → 句子的层级结构。

        节点 ID 遵循以下模式：doc:sec1:p2:s3，便于通过 ID 快速定位父节点。
        """
        # 用于生成唯一 ID 的全局计数器
        counters = {"section": 0, "paragraph": 0, "sentence": 0}

        # 使用提供的结构，若无则从纯文本自动生成
        sections = document.sections or sections_from_text(document)

        # 若需要，重建完整的文档文本
        document_text = document.text or "\n\n".join(
            paragraph.text for section in sections for paragraph in section.paragraphs
        )

        # 构建根文档节点
        root_metadata = dict(document.metadata)
        root_metadata.setdefault("document_id", document.document_id)
        root_metadata.setdefault("document_title", document.title)

        root = TreeNode(
            node_id=document.document_id,
            parent_id=None,
            kind=NodeKind.DOCUMENT,
            title=document.title,
            text=document_text,
            metadata=root_metadata,
        )

        # 构建章节节点
        for section in sections:
            counters["section"] += 1
            section_id = f"{document.document_id}:sec{counters['section']}"

            section_meta = dict(section.metadata)
            section_meta.update(
                {
                    "document_id": document.document_id,
                    "document_title": document.title,
                    "section_index": counters["section"],
                }
            )

            section_node = TreeNode(
                node_id=section_id,
                parent_id=root.node_id,
                kind=NodeKind.SECTION,
                title=section.title,
                text=section.title,
                metadata=section_meta,
            )
            root.children.append(section_node)

            # 构建段落节点
            for paragraph in section.paragraphs:
                counters["paragraph"] += 1
                paragraph_id = f"{section_id}:p{counters['paragraph']}"

                paragraph_meta = dict(paragraph.metadata)
                paragraph_meta.update(
                    {
                        "document_id": document.document_id,
                        "document_title": document.title,
                        "section_id": section_id,
                        "section_index": counters["section"],
                        "paragraph_index": counters["paragraph"],
                    }
                )

                paragraph_node = TreeNode(
                    node_id=paragraph_id,
                    parent_id=section_id,
                    kind=NodeKind.PARAGRAPH,
                    title=section.title,
                    text=paragraph.text,
                    metadata=paragraph_meta,
                )
                section_node.children.append(paragraph_node)

                # 构建句子节点
                sentences = paragraph.sentences or sentence_payloads_from_text(
                    paragraph.text
                )
                for sentence in sentences:
                    counters["sentence"] += 1
                    sentence_id = f"{paragraph_id}:s{counters['sentence']}"

                    sentence_meta = dict(sentence.metadata)
                    sentence_meta.update(
                        {
                            "document_id": document.document_id,
                            "document_title": document.title,
                            "section_id": section_id,
                            "paragraph_id": paragraph_id,
                            "sentence_index": counters["sentence"],
                        }
                    )

                    sentence_node = TreeNode(
                        node_id=sentence_id,
                        parent_id=paragraph_id,
                        kind=NodeKind.SENTENCE,
                        title=section.title,
                        text=sentence.text,
                        metadata=sentence_meta,
                    )
                    paragraph_node.children.append(sentence_node)

        return root

    async def _embed_tree(self, root: TreeNode) -> None:
        """
        为叶子节点计算嵌入向量，并向上传播至父节点。

        支持不同的段落嵌入模式：
        - "averaged": 段落嵌入 = 句子嵌入的平均值
        - "full": 段落嵌入 = 直接对段落文本进行嵌入
        - "both": 以平均嵌入作为主嵌入，将完整嵌入存入元数据
        """
        # 批量为所有叶子节点（句子）计算嵌入向量，以提高效率
        leaves = [node for node in self._flatten(root) if not node.children]
        if leaves:
            embeddings = await self._embedding_model.embed(
                [leaf.text for leaf in leaves]
            )
            for leaf, vector in zip(leaves, embeddings, strict=True):
                leaf.embedding = vector

        # 如果需要完整段落嵌入，则单独处理
        paragraphs = [
            node for node in self._flatten(root) if node.kind == NodeKind.PARAGRAPH
        ]

        if self._paragraph_embedding_mode in ("full", "both") and paragraphs:
            para_embeddings = await self._embedding_model.embed(
                [p.text for p in paragraphs]
            )
            para_full_map = {
                p.node_id: vec
                for p, vec in zip(paragraphs, para_embeddings, strict=True)
            }
        else:
            para_full_map = {}

        # 递归向上计算父节点的嵌入向量
        self._propagate_embeddings(root, para_full_map)

    def _propagate_embeddings(
        self, node: TreeNode, para_full_map: dict[str, np.ndarray] | None = None
    ) -> np.ndarray:
        """递归计算父节点的嵌入向量（子节点嵌入的平均值）。

        参数:
            node: 当前待处理的节点
            para_full_map: 段落节点 ID 到完整嵌入向量的映射（用于 "full"/"both" 模式）
        """
        if para_full_map is None:
            para_full_map = {}

        if node.embedding is not None:
            return node.embedding  # 叶子节点已嵌入

        # 递归处理子节点
        child_vectors = [
            self._propagate_embeddings(child, para_full_map) for child in node.children
        ]

        if not child_vectors:
            raise ValueError(f"节点 {node.node_id} 缺少嵌入向量。")

        # 计算子节点嵌入的平均值
        averaged_embedding = average_embeddings(child_vectors)

        # 处理段落节点的特殊嵌入模式
        if node.kind == NodeKind.PARAGRAPH and node.node_id in para_full_map:
            full_embedding = para_full_map[node.node_id]

            if self._paragraph_embedding_mode == "full":
                # 使用完整段落嵌入作为主嵌入
                node.embedding = full_embedding
            elif self._paragraph_embedding_mode == "both":
                # 以平均嵌入作为主嵌入，完整嵌入存入元数据
                node.embedding = averaged_embedding
                # 将完整嵌入以十六进制字节形式存入元数据
                node.metadata["full_embedding"] = full_embedding.tobytes().hex()
            else:
                # "averaged" 模式
                node.embedding = averaged_embedding
        else:
            # 非段落节点或无需完整嵌入的情况
            node.embedding = averaged_embedding

        return node.embedding

    def _flatten(self, node: TreeNode) -> Iterable[TreeNode]:
        """深度优先遍历树结构，返回所有节点。"""
        yield node
        for child in node.children:
            yield from self._flatten(child)

    def _to_stored(self, node: TreeNode) -> StoredNode:
        """将树节点转换为可持久化存储的 StoredNode 格式。"""
        if node.embedding is None:
            raise ValueError(f"节点 {node.node_id} 缺少嵌入向量。")

        return StoredNode(
            node_id=node.node_id,
            parent_id=node.parent_id,
            kind=node.kind,
            title=node.title,
            text=node.text,
            metadata=node.metadata,
            embedding=node.embedding,
            child_ids=[child.node_id for child in node.children],
        )
