import os
import re
import sys

from dotenv import load_dotenv
from typing import Any
from dataclasses import asdict

sys.path.insert(
    0,
    os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../")),
)

from src.index.spliters import split_paragraphs, split_sentences
from src.core.types import (
    DocumentPayload,
    ParagraphPayload,
    SectionPayload,
    SentencePayload,
)
from z_utils.logging_config import get_logger

load_dotenv()
logger = get_logger(__name__)

# 用于匹配 Markdown 标题的正则表达式（支持 # 到 ######）
HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")


def text_to_payload(
    *,
    document_id: str,
    title: str,
    text: str,
    metadata: dict[str, Any],
) -> DocumentPayload:
    """
    将纯文本转换为分层结构的 DocumentPayload。

    使用启发式分段方法进行处理：
    - 先将文本拆分为段落（paragraph）
    - 再将每个段落拆分为句子（sentence）
    """
    paragraphs = [
        ParagraphPayload(
            text=paragraph,
            sentences=[
                SentencePayload(text=sentence)
                for sentence in split_sentences(paragraph)
            ],
        )
        for paragraph in split_paragraphs(text)
    ]

    # 将所有段落归入一个以文档标题命名的默认 Section
    sections = [
        SectionPayload(
            title=title,
            paragraphs=paragraphs,
            metadata={"autogenerated": True},
        )
    ]

    return DocumentPayload(
        document_id=document_id,
        title=title,
        text=text,
        metadata=metadata,
        sections=sections,
    )


def markdown_to_payload(
    *,
    document_id: str,
    title: str,
    markdown_text: str,
    metadata: dict[str, Any],
) -> DocumentPayload:
    """
    将 Markdown 文本解析为分层结构的 DocumentPayload。

    解析策略：
    - 以 # 开头的标题行作为 Section（章节）的分界
    - 空白行用于分隔段落（Paragraph）
    - 如果文档中没有检测到任何标题，则回退使用纯文本解析函数
    """
    sections: list[SectionPayload] = []
    current_paragraph_lines: list[str] = []  # 当前正在累积的段落行
    current_title = title  # 当前 Section 的标题
    current_metadata: dict[str, Any] = {}  # 当前 Section 的元数据
    section_paragraphs: list[ParagraphPayload] = []  # 当前 Section 已累积的段落

    def flush_paragraph() -> None:
        """将当前累积的行保存为一个 Paragraph。"""
        if not current_paragraph_lines:
            return

        paragraph_text = "\n".join(current_paragraph_lines).strip()
        current_paragraph_lines.clear()

        # 将段落拆分为句子
        sentences = [
            SentencePayload(text=sentence)
            for sentence in split_sentences(paragraph_text)
        ]

        section_paragraphs.append(
            ParagraphPayload(
                text=paragraph_text,
                sentences=sentences,
            )
        )

    def flush_section() -> None:
        """将当前 Section 的所有段落保存到 sections 列表中。"""
        if section_paragraphs:
            sections.append(
                SectionPayload(
                    title=current_title,
                    paragraphs=list(section_paragraphs),  # 使用副本避免引用问题
                    metadata=dict(current_metadata),
                )
            )
            section_paragraphs.clear()

    # 逐行解析 Markdown 文本
    for line in markdown_text.splitlines():
        heading_match = HEADING_RE.match(line)

        if heading_match:
            # 遇到标题时，先结束当前段落和当前 Section，然后开始新的 Section
            flush_paragraph()
            flush_section()

            current_title = heading_match.group(2).strip()
            current_metadata = {"level": len(heading_match.group(1))}
            continue

        if not line.strip():
            # 空白行表示段落结束
            flush_paragraph()
            continue

        # 普通内容行，累积到当前段落
        current_paragraph_lines.append(line)

    # 处理文件结尾剩余的段落和 Section
    flush_paragraph()
    flush_section()

    # 如果整个文档中没有找到任何标题，则回退到纯文本解析方式
    if not sections:
        logger.info("未检测到 Markdown 标题，回退使用纯文本解析")
        sections = (
            text_to_payload(
                document_id=document_id,
                title=title,
                text=markdown_text,
                metadata=metadata,
            ).sections
            or []
        )

    return DocumentPayload(
        document_id=document_id,
        title=title,
        text=markdown_text,
        metadata=metadata,
        sections=sections,
    )


def payload_to_dict(payload: DocumentPayload) -> dict:
    """将 DocumentPayload 序列化为 JSON 兼容的字典。"""
    return asdict(payload)


def dict_to_payload(data: dict[str, Any]) -> DocumentPayload:
    """将字典（来自 JSON）反序列化为 DocumentPayload 对象。"""
    sections_data = data.get("sections") or []
    sections: list[SectionPayload] = []

    # 重建嵌套结构
    for section in sections_data:
        paragraphs: list[ParagraphPayload] = []

        for paragraph in section.get("paragraphs", []):
            sentences = [
                SentencePayload(
                    text=sentence.get("text", ""),
                    metadata=sentence.get("metadata", {}),
                )
                for sentence in paragraph.get("sentences", []) or []
            ]

            paragraphs.append(
                ParagraphPayload(
                    text=paragraph.get("text", ""),
                    sentences=sentences or None,
                    metadata=paragraph.get("metadata", {}),
                )
            )

        sections.append(
            SectionPayload(
                title=section.get("title", ""),
                paragraphs=paragraphs,
                metadata=section.get("metadata", {}),
            )
        )

    return DocumentPayload(
        document_id=data["document_id"],
        title=data.get("title", data["document_id"]),
        text=data.get("text", ""),
        metadata=data.get("metadata", {}),
        sections=sections or None,
    )


if __name__ == "__main__":
    """
    uv run src/index/parsers.py
    """
    import json
    from pathlib import Path
    from z_utils.hash_x import compute_mdhash_id

    file_path = "z_using_files/md/test_split2.md"

    def main() -> None:
        # 测试文档路径
        test_md_path: Path = Path(file_path)

        if not test_md_path.exists():
            logger.error(f"测试文档不存在：{test_md_path.resolve()}")
            return

        # 读取 Markdown 文件内容
        markdown_text: str = test_md_path.read_text(encoding="utf-8")
        document_id: str = compute_mdhash_id(markdown_text, prefix="doc_")
        title: str = os.path.splitext(test_md_path.name)[0]
        metadata: dict[str, Any] = {"source": "auto"}

        print("=" * 80)
        print("开始测试 Markdown 到 DocumentPayload 的转换")
        print("=" * 80)

        # 1. 测试 markdown_to_payload
        try:
            doc_payload: DocumentPayload = markdown_to_payload(
                document_id=document_id,
                title=title,
                markdown_text=markdown_text,
                metadata=metadata,
            )

            print(f"\n✓ markdown_to_payload 执行成功")
            print(f"文档 ID: {doc_payload.document_id}")
            print(f"标题: {doc_payload.title}")
            print(f"Section 数量: {len(doc_payload.sections or [])}")

            # 输出每个 Section 的概要信息
            for i, section in enumerate(doc_payload.sections or [], 1):
                print(f"\nSection {i}:")
                print(f"  标题: {section.title}")
                print(f"  元数据: {section.metadata}")
                print(f"  段落数量: {len(section.paragraphs)}")

                for j, para in enumerate(
                    section.paragraphs[:3], 1
                ):  # 只显示前 3 个段落作为示例
                    print(
                        f"    段落 {j}: {len(para.text)} 字符 | 句子数量: {len(para.sentences or [])}"
                    )
                    if para.sentences:
                        print(f"      示例句子: {para.sentences[0].text[:100]}...")

                if len(section.paragraphs) > 3:
                    print(f"    ... 剩余 {len(section.paragraphs) - 3} 个段落")

        except Exception as e:
            logger.exception("markdown_to_payload 执行失败")
            print(f"✗ markdown_to_payload 失败: {e}")

        print("\n" + "=" * 80)
        print("开始测试序列化与反序列化（payload <-> dict）")
        print("=" * 80)

        # 2. 测试 payload_to_dict 和 dict_to_payload（序列化循环）
        try:
            payload_dict: dict = payload_to_dict(doc_payload)
            print(f"✓ payload_to_dict 序列化成功，字典键数量: {len(payload_dict)}")

            # 保存为 JSON 文件（便于人工检查）
            output_json_path = Path("no_git_oic/test_output_payload.json")
            output_json_path.write_text(
                json.dumps(payload_dict, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )
            print(f"✓ 已将 DocumentPayload 保存至: {output_json_path.resolve()}")

            # 反序列化测试
            restored_payload: DocumentPayload = dict_to_payload(payload_dict)
            print(f"✓ dict_to_payload 反序列化成功")

            # 简单一致性检查
            assert restored_payload.document_id == doc_payload.document_id
            assert len(restored_payload.sections or []) == len(
                doc_payload.sections or []
            )
            print("✓ 序列化/反序列化一致性验证通过")

        except Exception as e:
            logger.exception("序列化/反序列化测试失败")
            print(f"✗ 序列化测试失败: {e}")

        # 3. 可选：纯文本回退测试（如果 Markdown 中无标题）
        print("\n" + "=" * 80)
        print("额外测试：纯文本回退模式（text_to_payload）")
        print("=" * 80)

        try:
            plain_doc = text_to_payload(
                document_id=document_id + "_plain",
                title=title + "（纯文本模式）",
                text=markdown_text[:2000],  # 取前 2000 字符作为示例
                metadata=metadata,
            )
            print(
                f"✓ text_to_payload 执行成功，默认 Section 数量: {len(plain_doc.sections or [])}"
            )
        except Exception as e:
            print(f"✗ text_to_payload 测试失败: {e}")

    main()
